version: "3"
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=simple_blog_api
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_USER=postgres
  api:
    depends_on:
      - postgres
    image: adithyakk94/simple-blog-api
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DB=simple_blog_api
      - POSTGRES_PASSWORD=postgres_password